baseURL = 'https://example.org/'
relativeURLs = true
languageCode = 'en-us'
title = 'Git Mastery'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookSection = 'docs'
BookRepo = 'https://github.com/git-mastery/website'

[markup]
[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.after]]
name = "Problems"
url = "https://github.com/git-mastery/problems-directory"
weight = 10

[[menu.after]]
name = "Progress Dashboard"
url = "https://git-mastery.github.io/progress-dashboard"
weight = 11
