baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Git Mastery'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
BookSection = 'docs'
BookRepo = 'https://github.com/git-mastery/website'

[markup]
[markup.goldmark.renderer]
unsafe = true
